[Interface]
PrivateKey = GK9CMe8rKjE3wllvt/arniE+x80XlPI4MgHkHmAd+EE=
Address = 10.23.63.2/24
DNS = 10.23.63.1

[Peer]
PublicKey = dIE+6P+gHWZX2HYlDRjRKnwaFVmDZzr4eZvms5jcgRM=
PresharedKey = bos8djhpT0ApiRJ4QdkZXYTbMeptcz2eNVfIHfisdvo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 133.218.53.5:60716
